fixed issue with -uncaught typeerror: applyToAll is not a function at htmlinputelement.onchange-. turned out it was an issue with the label and input having the same id as the function name